#+TITLE: Todolist-dengan-vanilla-js

Belajar JavaScript dan MVC sekaligus studi kasus membuat todo list

Sebelum kita membuat todo list, alangkah lebih baiknya, kita pahami terlebih dahulu syntaxs.

* Syntaxs JavaScript

*** Variable
Variable adalah tempat untuk menyimpan data, dengan menyimpan data ke variable, kita bisa menggnakan lagi dengan menyebut nama variable nya.

Contoh membuat variable
#+BEGIN_SRC shell
var a = 123;
let b = "halo dunia";
const c = true
#+END_SRC

*** Array
Array adalah tempat atau wajah untuk menyimpan tipe data seperti, number, string dan boolean.

Contoh membuat array
#+BEGIN_SRC shell

const c = [120,"Halo dunia",true atua fals1e];
#+END_SRC

*** If
If untuk membuat penyataan jika kondisi benar atau jika kondisi salah.

Contoh membuat if
#+BEGIN_SRC shell
if(6.5 > 7){
    concole.log("lulus");
} else {
    console.log("tidak lulus");
}
#+END_SRC

*** While
While untuk membuat pengulangan kondisi yang kita inginkan.

Contoh membuat while
#+BEGIN_SRC shell
let a = 0;
while(a <=10){
    console.log("nilai ke " + a + "a");
    a++
}
#+END_SRC

*** Function
Function merupakan satu blok program atua kode yang akan berjalan saat kita panggil.
Contoh Membuat function
#+BEGIN_SRC shell
fnction tambah(a,b){
    return a + b;
}
tambah(12,11);
#+END_SRC

*** MVC
MVC (Model-View-Controller) merupakan perkelompokan program atau kode yang masing-masing memiliki fungsingya sendiri.

Tiga fungsi sebagai berikut.
1. Model: Mengola data dan logika bisnis.
2. View: Menangani tata letak dan tampilan
3. Controller: Merutekan perintah ke model dan view
Lebih lanjut bisa kunjungi website  di bawah ini 
[[https://developer.mozilla.org/en-US/docs/Glossary/MVC][https://developer.mozilla.org/en-US/docs/Glossary/MVC]]